version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.springframework.boot:spring-boot-starter
    versions:
    - 2.4.2
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.springframework.boot:spring-boot-autoconfigure
    versions:
    - 2.4.2
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.springframework.boot:spring-boot-starter-cache
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.springframework.boot:spring-boot-starter-validation
    versions:
    - 2.4.2
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.springframework.boot:spring-boot-starter-data-redis
    versions:
    - 2.4.2
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.springframework.boot:spring-boot-starter-jdbc
    versions:
    - 2.4.2
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.springframework.boot:spring-boot-starter-aop
    versions:
    - 2.4.2
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.springframework.boot:spring-boot-starter-webflux
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.springframework.boot:spring-boot-starter-test
    versions:
    - 2.4.2
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.springframework.boot
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: io.projectreactor:reactor-bom
    versions:
    - 2020.0.4
    - 2020.0.5
  - dependency-name: com.github.kt3k.coveralls
    versions:
    - 2.10.2
    - 2.11.0
  - dependency-name: org.ehcache:ehcache
    versions:
    - 3.9.0
    - 3.9.1
    - 3.9.2
  - dependency-name: org.springframework.cloud:spring-cloud-dependencies
    versions:
    - Hoxton.SR10
  - dependency-name: org.springframework.boot:spring-boot-starter-web
    versions:
    - 2.4.2
  - dependency-name: com.h2database:h2
    versions:
    - 1.4.200
